name: Build and Test
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19
    - name: Build with Maven
      run: mvn test-compile

    - name: Test with Maven
      run: mvn run Demo
